#pragma once

#define SHADER_HANDLE_DEFERREDFX_TEXTURE_GBUFFER_ALBEDO		"g_DeferredAlbedoTex"
#define SHADER_HANDLE_DEFERREDFX_TEXTURE_GBUFFER_NORMAL		"g_DeferredNormalTex"
#define SHADER_HANDLE_DEFERREDFX_TEXTURE_GBUFFER_DEPTH		"g_DeferredDepthTex"
#define SHADER_HANDLE_DEFERREDFX_TEXTURE_GBUFFER_SPECULAR	"g_DeferredSpecularTex"

#define SHADER_HANDLE_DEFERREDFX_TEXTURE_LIGHTACC_DIFFUSE	"g_DeferredLightDiffuseTex"
#define SHADER_HANDLE_DEFERREDFX_TEXTURE_LIGHTACC_SPECULAR	"g_DeferredLightSpecularTex"


#define SHADER_TECH_DEFERREDFX_GBUFFERDEFAULT		"DeferredGBufferDefault"
enum SHADER_PASS_DEFERREDFX_GBUFFER_DEFAULTTECH
{
	SPDGD_DEFAULT,
};

#define SHADER_TECH_DEFERREDFX_GBUFFERSKINNING		"DeferredGBufferSkinning"
enum SHADER_PASS_DEFERREDFX_GBUFFER_SKINNINGTECH
{
	SPDGS_DEFAULT,
};


#define SHADER_TECH_DEFERREDFX_LIGHTACC_DIRECTIONAL "LightAccDirectional"
#define SHADER_TECH_DEFERREDFX_LIGHTACC_POINT		"LightAccPoint"

#define SHADER_TECH_DEFERREDFX_COMBINE	"DeferredCombine"